### ISSUE TITLE
[Epic] Milestone 1

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/WalletConnectFlutterV2#100]
## Implementation Path
This is intended as an overview of critical path work for the Web3Modal Flutter SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

### Features
- [x] Show mobile wallets list from Explorer API
- [x] Show QR Code
- [x] Customizable cloud PROJECT_ID
- [x] Connect with Wallet
- [x] Add Eth_methods to example
- [ ] https://github.com/WalletConnect/WalletConnectFlutterV2/issues/105
- [ ] Reuse session
- [ ] Add contract methods to example
- [ ] Create docs in https://docs.walletconnect.com
- [ ] [explorerRecommendedWalletIds](https://docs.walletconnect.com/2.0/web3modal/options#explorerrecommendedwalletids-optional)
- [ ] [explorerExcludedWalletIds](https://docs.walletconnect.com/2.0/web3modal/options#explorerexcludedwalletids-optional)
- [ ]  Improve Animations + UI
- [ ] Add “What is a wallet” screen

### Next steps
https://github.com/WalletConnect/web3modal-react-native/issues/27
